from typing import Protocol, List, Optional
from app.models.person import Person


class PersonService(Protocol):
    def create(self, person: Person) -> Person: ...
    def read_by_id(self, person_id: int) -> Optional[Person]: ...
    def read_all(self) -> List[Person]: ...
    def update(self, person_id: int, data: Person) -> Optional[Person]: ...
    def delete(self, person_id: int) -> Optional[Person]: ...
